language: python

python:
    - 2.7
    - 3.3
    - 3.4

install:
  # install deps
  - pip install -r requirements.txt
  - pip install fastcluster
  - pip install twisted
  - pip install python-coveralls
  - pip list

script:
  - nosetests

after_success:
  - coveralls
