language: python

python:
    - 3.4
    - 3.5
    - 3.6

install:
  # install deps
  - pip install -r requirements.txt
  - pip install fastcluster
  - pip install twisted
  - pip install python-coveralls
  - pip list

script:
  - nosetests

after_success:
  - coveralls
