language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

before_install:
  - python -V
  - pip list

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip list
  - pip install -r requirements.txt
  - pip list

script:
  - nosetests

after_script:
  - echo "install"
