language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - pip list

install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas scipy twisted requests psycopg2 nose mock coverage numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH

  #- pip install --upgrade pip
  #- pip install --upgrade setuptools
  #- pip list
  #- pip install --upgrade numpy
  #-# pip install --upgrade scipy
  - pip install -r requirements.txt
  #- pip install twisted
  #- pip list

script:
  - nosetests

after_script:
  - echo "install"
